### ISSUE TITLE
Jekyll environment fails to install

### ISSUE THREAD

**Issue by Ravenwater** [fossi-foundation/fossi-foundation.github.io#55]
When trying to install the environment encountering this error:
```
stillwater@sw-laptop-251:~/dev/forks/fossi-foundation.github.io$ sudo gem update --system
Updating rubygems-update
Fetching rubygems-update-3.3.8.gem
Successfully installed rubygems-update-3.3.8
Parsing documentation for rubygems-update-3.3.8
Installing ri documentation for rubygems-update-3.3.8
Installing darkfish documentation for rubygems-update-3.3.8
Done installing documentation for rubygems-update after 154 seconds
Parsing documentation for rubygems-update-3.3.8
Done installing documentation for rubygems-update after 0 seconds
Installing RubyGems 3.3.8
Traceback (most recent call last):
        5: from setup.rb:22:in `<main>'
        4: from setup.rb:22:in `require'
        3: from /var/lib/gems/2.7.0/gems/rubygems-update-3.3.8/lib/rubygems.rb:1325:in `<top (required)>'
        2: from /var/lib/gems/2.7.0/gems/rubygems-update-3.3.8/lib/rubygems.rb:1325:in `require'
        1: from /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:49:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:50:in `<class:Specification>': undefined method `rubyforge_project=' for class `Gem::Specification' (NameError)
        3: from setup.rb:22:in `<main>'
        2: from setup.rb:22:in `require'
        1: from /var/lib/gems/2.7.0/gems/rubygems-update-3.3.8/lib/rubygems.rb:1321:in `<top (required)>'
/var/lib/gems/2.7.0/gems/rubygems-update-3.3.8/lib/rubygems.rb:1334:in `rescue in <top (required)>': undefined method `rubyforge_project=' for class `Gem::Specification' (NameError)
Loading the rubygems/defaults/operating_system.rb file caused an error. This file is owned by your OS, not by rubygems upstream. Please find out which OS package this file belongs to and follow the guidelines from your OS to report the problem and ask for help.
```

**Comment by imphil** [comment]
I just saw that, and I guess it doesn't matter any more, but: Don't run "gem update" as root.
